### ISSUE TITLE
No results when scanning CycloneDX file from cargo-cyclonedx

### ISSUE THREAD

**Issue by Feelemoon** [devops-kung-fu/bomber#127]
When scanning a CycloneDX file from https://github.com/CycloneDX/cyclonedx-rust-cargo no output is generated. 

It would be nice, if the user is informed if the BOM has been scanned or not (for some reason).

**Comment by djschleen** [comment]
Thanks for the issue! We'll take a look.

**Comment by djschleen** [comment]
@Feelemoon I used [[this](https://github.com/CycloneDX/cyclonedx-rust-cargo/blob/main/cyclonedx-bom/tests/data/1.3/valid-bom-1.3.json)](https://github.com/CycloneDX/cyclonedx-rust-cargo/blob/main/cyclonedx-bom/tests/data/1.3/valid-bom-1.3.json] SBOM from that project and although it is valid JSON, it had an empty Purl in it which caused a problem. Bomber threw a "scheme missing" error - which doesn't say much. In the JSON the issue is with the second component. It has no Purl and therefore can't be scanned:

<img width="511" alt="image" src="https://user-images.githubusercontent.com/32048395/222291267-8824241e-158a-4ed3-9ffe-f28c775b1267.png">

I was testing with the new 0.4.1 version of bomber which we just released, and we did put fix some output issues when nothing was found.  Here is a debug screenshot:

<img width="1152" alt="image" src="https://user-images.githubusercontent.com/32048395/222290837-388aa64c-5a2c-4cdb-b5f5-a8e1f1090322.png">

Not sure if you were testing another SBOM, but could you try running 0.4.1 on it?

**Comment by djschleen** [comment]
#137 compensates for this use case by removing empty or invalid purls.
